# -*- coding: utf-8 -*-
"""APROPIACION_MORA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5T0o8SH44U-CyP2zgrrf08tBCeL8wP2

APROPIACION

    Realiza una función que tome una lista de números enteros y devuelva dos listas ordenadas. La primera con los números pares y la segunda con los números impares.
"""

def separar_pares_impares(numeros):
    pares = []
    impares = []

    for numero in numeros:
        if numero % 2 == 0:
            pares.append(numero)
        else:
            impares.append(numero)

    for i in range(1, len(pares)):
        clave = pares[i]
        j = i - 1
        while j >= 0 and clave < pares[j]:
            pares[j + 1] = pares[j]
            j -= 1
        pares[j + 1] = clave

    for i in range(1, len(impares)):
        clave = impares[i]
        j = i - 1
        while j >= 0 and clave < impares[j]:
            impares[j + 1] = impares[j]
            j -= 1
        impares[j + 1] = clave

    return pares, impares


lista = [4, 7, 2, 9, 12, 3, 8]
pares, impares = separar_pares_impares(lista)
print("Pares:", pares)
print("Impares:", impares)

"""Realiza una función que reciba una palabra y devuelva un diccionario donde las claves sean las diferentes letras que se encuentran en la palabra y los valores sean el número de veces que se repite cada letra en la palabra"""

def contar_letras(palabra):
    conteo = {}

    for letra in palabra:
        if letra in conteo:
            conteo[letra] += 1
        else:
            conteo[letra] = 1

    return conteo


resultado = contar_letras("programacion")
print("Conteo de letras:", resultado)