# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPvy1xtCANHUJ_LhJCs8pryE-U3yfym_

*EJERCICIOS FINALES*

Ejercicio 1: Calculadora Avanzada
Descripción:
Crea una función que actúe como calculadora. La función recibirá dos números y un operador (por ejemplo, '+', '-', '*', '/', '**', '//') para realizar la operación correspondiente.

Utiliza estructuras de control (if/else) para seleccionar la operación a realizar.
Usa manejo de excepciones para controlar errores como la división por cero y entradas no numéricas.
Puedes importar el módulo math para operaciones adicionales si es necesario.
Ejemplo de salida:

Ingrese el primer número: 10 Ingrese el segundo número: 5 Ingrese el operador (+, -, *, /, **, //): / Resultado: 10 / 5 = 2.0
"""

def calculadora():
    try:
        num1 = int(input("Ingrese el primer número: "))
        num2 = int(input("Ingrese el segundo número: "))
        operador = input("Ingrese el operador (+, -, *, /, **, //): ")

        if operador == '+':
            resultado = num1 + num2
        elif operador == '-':
            resultado = num1 - num2
        elif operador == '*':
            resultado = num1 * num2
        elif operador == '/':
            resultado = num1 / num2
        elif operador == '**':
            resultado = num1 ** num2
        elif operador == '//':
            resultado = num1 // num2
        else:
            print("Operador no válido.")
            return

        print(f"Resultado: {num1} {operador} {num2} = {resultado}")
    except ZeroDivisionError:
        print("Error: División por cero.")
    except ValueError:
        print("Error: Entrada no válida.")

calculadora()

"""Ejercicio 2: Administrador de Inventarios
Descripción:
Desarrolla un sistema para gestionar el inventario de productos usando un diccionario donde cada clave es el nombre del producto y su valor la cantidad en stock.

Implementa funciones para agregar, actualizar y eliminar productos.
Utiliza estructuras de control para recorrer y mostrar el inventario.
Incluye manejo de excepciones para capturar intentos de actualizar o eliminar un producto inexistente.
Ejemplo de salida:
Inventario inicial: {'manzanas': 50, 'naranjas': 30, 'peras': 20} Actualizando stock de 'peras' a 25... Producto 'bananas' agregado con 40 unidades. Eliminando 'naranjas'... Inventario final: {'manzanas': 50, 'peras': 25, 'bananas': 40}
"""

inventario = {
    'manzanas': 10,
    'peras': 5,
    'naranjas': 8
}

def agregar_producto(producto, cantidad):
    if producto in inventario:
        inventario[producto] += cantidad
    else:
        inventario[producto] = cantidad
    print(f'Se han agregado {cantidad} unidades de {producto}.')
    print(f'Inventario actualizado: {inventario}')

def eliminar_producto(producto, cantidad):
    if producto in inventario:
        if inventario[producto] >= cantidad:
            inventario[producto] -= cantidad
            print(f'Se han eliminado {cantidad} unidades de {producto}.')
        else:
            print(f'Error: No hay suficientes unidades de {producto} para eliminar.')
    else:
        print(f'Error: El producto {producto} no existe en el inventario.')
    print(f'Inventario actualizado: {inventario}')

def mostrar_inventario():
    print('Inventario actual:')
    for producto, cantidad in inventario.items():
        print(f'{producto}: {cantidad} unidades')

    else:
        print(f'Error: El producto {producto} no existe en el inventario.')

opcion = input('Que quiere hacer? (agregar, eliminar, mostrar, salir): ')
while opcion != 'salir':
    if opcion == 'agregar':
        producto = input('Ingrese el nombre del producto: ')
        cantidad = int(input('Ingrese la cantidad a agregar: '))
        agregar_producto(producto, cantidad)
    elif opcion == 'eliminar':
        producto = input('Ingrese el nombre del producto: ')
        cantidad = int(input('Ingrese la cantidad a eliminar: '))
        eliminar_producto(producto, cantidad)
    elif opcion == 'mostrar':
        mostrar_inventario()
    else:
        print('Opción no válida. Intente de nuevo.')
    opcion = input('Que quiere hacer? (agregar, eliminar, mostrar, salir): ')
    print('Gracias por usar el sistema.')

"""Ejercicio 3: Análisis de Texto
Descripción:
Crea una función que reciba una cadena de texto y calcule la frecuencia de cada palabra en el mismo.

Convierte el texto a minúsculas y separa las palabras usando algún método (puedes utilizar expresiones regulares con el módulo re).
Emplea un diccionario para almacenar la palabra (clave) y su frecuencia (valor).
Controla excepciones en caso de que el usuario no ingrese ningún texto o ingrese caracteres inesperados.
Ejemplo de salida:
Ingrese un texto: "Hola mundo, hola a todos en el mundo" Frecuencia de palabras: hola: 2 mundo: 2 a: 1 todos: 1 en: 1 el: 1
"""

def analisis_texto():
    try:
        texto = input("Ingrese un texto: ").lower()
        if not texto.strip():
            raise ValueError("Texto vacío")

        for char in ",.;:!?¿¡\"'()[]{}":
            texto = texto.replace(char, " ")

        palabras = texto.split()
        frecuencia = {}

        for palabra in palabras:
            frecuencia[palabra] = frecuencia.get(palabra, 0) + 1

        print("Frecuencia de palabras:")
        for palabra, freq in frecuencia.items():
            print(f"{palabra}: {freq}")
    except ValueError as e:
        print("Error:", e)

analisis_texto()

"""Ejercicio 4: Conversor de Unidades
Descripción:
Desarrolla un conjunto de funciones para convertir unidades métricas. Por ejemplo:

De centímetros a pulgadas.
De kilómetros a millas.
Utiliza estructuras de control para verificar que la entrada sea numérica, y maneja excepciones cuando el usuario ingrese datos inválidos.
Ejemplo de salida:
Seleccione la conversión:

Centímetros a pulgadas

Kilómetros a millas Opción: 1 Ingrese la cantidad en centímetros: 100 Resultado: 100 cm = 39.37 pulgadas
"""

def conversor_unidades():
    print("Seleccione la conversión:")
    print("1. Centímetros a pulgadas")
    print("2. Kilómetros a millas")

    try:
        opcion = int(input("Opción: "))
        if opcion == 1:
            cm = float(input("Ingrese la cantidad en centímetros: "))
            pulgadas = cm / 2.54
            print(f"Resultado: {cm} cm = {pulgadas:.2f} pulgadas")
        elif opcion == 2:
            km = float(input("Ingrese la cantidad en kilómetros: "))
            millas = km * 0.621371
            print(f"Resultado: {km} km = {millas:.2f} millas")
        else:
            print("Opción no válida.")
    except ValueError:
        print("Entrada inválida.")

conversor_unidades()

"""Ejercicio 5: Juego "Adivina el Número"
Descripción:
Implementa un juego en el que la computadora selecciona aleatoriamente un número en un rango (por ejemplo, 1 a 50) y el usuario debe adivinarlo.

Emplea el módulo random para generar el número secreto.
Utiliza un bucle que permita múltiples intentos, con retroalimentación indicando si el número ingresado es mayor o menor que el secreto.
Gestiona excepciones para capturar entradas no numéricas.
Ejemplo de salida:
¡Bienvenido al juego "Adivina el Número"! Estoy pensando en un número entre 1 y 50. Intento 1 - Ingresa tu número: 25 El número secreto es mayor. Intento 2 - Ingresa tu número: 35 El número secreto es menor. Intento 3 - Ingresa tu número: 30 ¡Felicidades! Has adivinado el número secreto: 30
"""

import random

def adivina_numero():
    print('¡Bienvenido al juego "Adivina el Número"!')
    secreto = random(1, 50)
    intento = 0
    while True:
        intento += 1
        try:
            num = int(input(f"Intento {intento} - Ingresa tu número: "))
            if num < secreto:
                print("El número secreto es mayor.")
            elif num > secreto:
                print("El número secreto es menor.")
            else:
                print(f"¡Felicidades! Has adivinado el número secreto: {secreto}")
                break
        except ValueError:
            print("Entrada no válida. Por favor, ingresa un número.")

adivina_numero()

"""Ejercicio 6: Calculadora de Factorial
Descripción:
Crea una función que calcule el factorial de un número entero ingresado por el usuario.

La función debe utilizar estructuras de control para iterar (o una solución recursiva) y calcular el factorial.
Implementa manejo de excepciones para asegurarte de que el número ingresado es entero y no negativo.
Ejemplo de salida:
Ingrese un número entero para calcular su factorial: 5 El factorial de 5 es 120
"""

def factorial():
    try:
        n = int(input("Ingrese un número entero para calcular su factorial: "))
        if n < 0:
            raise ValueError("El número debe ser no negativo.")
        resultado = 1
        for i in range(1, n + 1):
            resultado *= i
        print(f"El factorial de {n} es {resultado}")
    except ValueError as e:
        print("Error:", e)

factorial()

"""Ejercicio 7: Manejo de Fechas y Horas
Descripción:
Desarrolla una función que reciba una fecha ingresada por el usuario en formato "DD/MM/AAAA" y determine cuántos días faltan para esa fecha a partir de hoy.

Importa el módulo datetime para trabajar con fechas.
Utiliza estructuras de control para validar el formato y maneja excepciones en caso de error en el ingreso de la fecha.
Ejemplo de salida:
Ingrese una fecha (DD/MM/AAAA): 25/12/2023 Faltan 150 días para el 25/12/2023.
"""

from datetime import datetime

def dias_para_fecha():
    try:
        entrada = input("Ingrese una fecha (DD/MM/AAAA): ")
        fecha_obj = datetime(entrada, "%d/%m/%Y")
        hoy = datetime.today()
        diferencia = (fecha_obj - hoy).days
        if diferencia >= 0:
            print(f"Faltan {diferencia} días para el {entrada}.")
        else:
            print(f"La fecha {entrada} ya ha pasado.")
    except ValueError:
        print("Formato de fecha incorrecto.")

dias_para_fecha()

"""Ejercicio 8: Registro de Estudiantes
Descripción:
Implementa un sistema que gestione un registro de estudiantes utilizando un diccionario, donde la clave sea el nombre y el valor la calificación.

Crea funciones para agregar un estudiante, actualizar la calificación, eliminar estudiantes y listar todo el registro.
Utiliza un bucle para mostrar un menú interactivo al usuario.
Maneja excepciones para gestionar errores en la selección de opciones o al intentar modificar un estudiante inexistente.
Ejemplo de salida:
Registro de estudiantes inicial: {'Ana': 90, 'Luis': 78, 'Carlos': 85}

Menú:

Agregar estudiante

Actualizar calificación

Eliminar estudiante

Listar estudiantes

Salir

Opción: 2 Ingrese el nombre del estudiante: Luis Ingrese la nueva calificación: 82 Estudiante actualizado: Luis - 82

Registro final: {'Ana': 90, 'Luis': 82, 'Carlos': 85}

"""

def registro_estudiantes():
    estudiantes = {'Ana': 90, 'Luis': 78, 'Carlos': 85}
    while True:
        print("\nMenú:\n1. Agregar estudiante\n2. Actualizar calificación\n3. Eliminar estudiante\n4. Listar estudiantes\n5. Salir")
        try:
            opcion = int(input("Opción: "))
            if opcion == 1:
                nombre = input("Ingrese el nombre del estudiante: ")
                calif = int(input("Ingrese la calificación: "))
                estudiantes[nombre] = calif
            elif opcion == 2:
                nombre = input("Ingrese el nombre del estudiante: ")
                if nombre in estudiantes:
                    calif = int(input("Ingrese la nueva calificación: "))
                    estudiantes[nombre] = calif
                    print(f"Estudiante actualizado: {nombre} - {calif}")
                else:
                    print("Estudiante no encontrado.")
            elif opcion == 3:
                nombre = input("Ingrese el nombre del estudiante: ")
                del estudiantes[nombre]
            elif opcion == 4:
                print("Registro de estudiantes:", estudiantes)
            elif opcion == 5:
                break
            else:
                print("Opción no válida.")
        except ValueError:
            print("Entrada inválida.")
        except KeyError:
            print("Estudiante no encontrado.")

registro_estudiantes()

"""Ejercicio 9: Generador de Contraseñas Aleatorias
Descripción:
Crea una función que genere una contraseña aleatoria de una longitud especificada por el usuario.

Utiliza el módulo random junto con la biblioteca string para construir la contraseña a partir de letras (mayúsculas y minúsculas), dígitos y caracteres especiales.
Valida la entrada y maneja excepciones para asegurarte de que la longitud es un número entero positivo.
Ejemplo de salida:
Ingrese la longitud deseada para la contraseña: 10 Contraseña generada: A8b#K3d!Qz
"""

import random
import string

def generar_contraseña():
    try:
        longitud = int(input("Ingrese la longitud deseada para la contraseña: "))
        if longitud <= 0:
            raise ValueError("La longitud debe ser positiva.")
        caracteres = string.ascii_letters + string.digits + string.punctuation
        contraseña = ''.join(random.choice(caracteres) for _ in range(longitud))
        print("Contraseña generada:", contraseña)
    except ValueError as e:
        print("Error:", e)

generar_contraseña()

"""Ejercicio 10: Buscador de Archivos en un Directorio
Descripción:
Desarrolla una función que reciba el nombre de un directorio y una subcadena para buscar archivos cuyo nombre la contenga.

Utiliza el módulo os para listar el contenido del directorio.
Aplica estructuras de control para filtrar los archivos según la subcadena.
Implementa manejo de excepciones para controlar errores como directorio no existente o permisos insuficientes.
Ejemplo de salida:
Ingrese la ruta del directorio: /ruta/al/directorio Ingrese la subcadena a buscar: reporte Archivos encontrados que contienen "reporte":

reporte_enero.pdf

reporte_febrero.xlsx

resumen_reporte.txt
"""

import os

def buscar_archivos():
    try:
        ruta = input("Ingrese la ruta del directorio: ")
        subcadena = input("Ingrese la subcadena a buscar: ")
        archivos = os.listdir(ruta)
        encontrados = [f for f in archivos if subcadena in f]
        print(f'Archivos encontrados que contienen "{subcadena}":')
        for archivo in encontrados:
            print(archivo)
    except FileNotFoundError:
        print("El directorio no existe.")
    except PermissionError:
        print("Permiso denegado.")
    except Exception as e:
        print("Error:", e)

buscar_archivos()